name: Backwards Compatibility

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10, 12, 14]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install --ignore-scripts

      - name: Install types
        run: "npm install @types/node@${{ matrix.node }}"

      - name: Compile
        run: npx tsc --noEmit
