name: Unit Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: restore lerna
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Test
        run: npm run test
